### PR TITLE
Deactivation before activation should not return as non-zero

### PR DESCRIPTION
**Pull request by yyuu**
@blueyed is this just working as you expected in #116?

### CODE REVIEW

**Comment by blueyed** [comment]
So this is meant to replace #116?
Will give it a try.

**Comment by yyuu** [comment]
@blueyed Right. Gimme some feedback once you tried.

**Comment by blueyed** [comment]
@yyuu 
Works for me, thanks!

**Comment by yyuu** [comment]
okay~

**Pull request merged**
