### PR TITLE
Evaluate ${PATH} when outputted code is eval'd.

### PR DESCRIPTION
**Pull request by seanfisk**
I noticed this because my shell configurations run `pyenv virtualenv-init` at a different time than they run the code it produces, and this causes a problem.

I am guessing that my commit is the way it was intended to be written, based on the fish line and the [similar lines in `pyenv-init`](https://github.com/yyuu/pyenv/blob/master/libexec/pyenv-init#L87). But let me know if my presumption is incorrect.

Thanks!

### CODE REVIEW

**Comment by yyuu** [comment]
I couldn't get your situation and the intention for this change. Basically deferring rhe evaluation of PATH won't help nothing. And alao, CI is failing by this.

**Comment by seanfisk** [comment]
Sorry about the CI; I fixed that.

Essentially the problem is about consistency:
```bash
$ export PATH=/just-testing:/usr/local/bin:/usr/bin:/bin
$ pyenv virtualenv-init - fish
setenv PATH '/usr/local/Cellar/pyenv-virtualenv/20160202/shims' $PATH;
… more output …
$ pyenv virtualenv-init - bash
export PATH="/usr/local/Cellar/pyenv-virtualenv/20160202/shims:/usr/local/Cellar/pyenv/20160202/libexec:/just-testing:/usr/local/bin:/usr/bin:/bin";
… more output …
```
In this case, `${PATH}` is not expanded for fish, but it *is* already expanded for Bash (and zsh). `pyenv` itself doesn't do this:
```bash
$ pyenv init - bash
export PATH="/Users/sean/.pyenv/shims:${PATH}"
```
My PR changes this thusly:
```bash
$ pyenv virtualenv-init - bash
export PATH="/usr/local/Cellar/pyenv-virtualenv/20160202/shims:${PATH}";
… more output …
```
Although this pull request is about fixing this, it also helps my situation. I run `pyenv init -` and `pyenv virtualenv-init -` beforehand, and then eval the code they output when my shells start. That's how I noticed this problem, since `${PATH}` is interpreted when `pyenv virtualenv-init -` is run, not when the code it generates is evaluated.

I appreciate you looking at this! Let me know what you think.

**Comment by blueyed** [comment]
I think it makes sense, but should go through rbenv (pyenv's upstream) probably.

**Comment by seanfisk** [comment]
@blueyed That would be fine with me, but what is the upstream repo? This is an issue with pyenv-virtualenv, and rbenv doesn't use virtualenv…

Thanks for taking a look!

**Comment by yyuu** [comment]
There's similar code in pyenv-init and I think @blueyed meant it. Although it's already prepared to respect `$PATH` of original shell. I think you don't have to care about it.

https://github.com/yyuu/pyenv/blob/v20160303/libexec/pyenv-init#L93

@blueyed please let me know if my assumption was wrong.

**Comment by seanfisk** [comment]
@yyuu Ok, thanks!

**Pull request merged**
