### PR TITLE
change minor typo in bin/pyenv-sh-activate

### PR DESCRIPTION
**Pull request by shangsunset**

### CODE REVIEW

**Comment by yyuu** [comment]
Umm. CI's failing. If you're not familiar with bats, I will merge abnd fix them later.

**Comment by shangsunset** [comment]
Yea, i dont know how Cl works. wish i chould help.

**Comment by yyuu** [comment]
@shangsunset I guess you need to fix extra 3 lines to pass CI.

https://github.com/shangsunset/pyenv-virtualenv/blob/d26852e274f9c3eea25f657ad5af1cc5f8ecf119/test/activate.bats#L146
https://github.com/shangsunset/pyenv-virtualenv/blob/d26852e274f9c3eea25f657ad5af1cc5f8ecf119/test/activate.bats#L226
https://github.com/shangsunset/pyenv-virtualenv/blob/d26852e274f9c3eea25f657ad5af1cc5f8ecf119/test/activate.bats#L251

**Comment by shangsunset** [comment]
I see. Thank you.

**Comment by yyuu** [comment]
:+1:

**Pull request merged**
